/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import clase.Categoria;
import clase.Estadistica;
import clase.Jugador;
import clase.Opcion;
import clase.Pregunta;
import clase.Ronda;
import com.mysql.jdbc.Connection;
import java.awt.Component;
import java.awt.Panel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import controlador.*;
import conexion.Conectar;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Random;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JRadioButton;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yo
 */
public class Principal extends javax.swing.JFrame {
    ControladorJugador control;
    String sNick;
    int nId;
    DefaultTableModel modelo=null;
    
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        IniPant();
        Visibles();
        HabMant();
        HabOpc(false);
        try {
            LlenarHistorico();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LlenarHistorico() throws SQLException, ClassNotFoundException{
        tblRanking.setModel(new DefaultTableModel());
        String[] columnas={"Jugador","Nivel","Premio","Tipo"};
        String[] registros=new String[4];
        modelo=new DefaultTableModel(null,columnas);
        modelo.setColumnIdentifiers(columnas);
        tblRanking.setModel(modelo);
        Conectar cnn=new Conectar();
        ArrayList<Estadistica> estadisticas=new ArrayList<Estadistica>();
        ControladorEstadistica conEsta=new ControladorEstadistica();
        estadisticas=conEsta.getAllEstadistica(cnn.obtener());
        if(estadisticas.size()>0){
            for(Estadistica estadistica:estadisticas){
              registros[0]=estadistica.getJugador();
              registros[1]=Integer.toString(estadistica.getIdRonda());
              registros[2]=Integer.toString(estadistica.getPremio());
              if(estadistica.getTipo_P()==0){
                  registros[3]="Puntos";
              }else{
                registros[3]="Dinero";
              }
              
              modelo.addRow(registros);
            }
            tblRanking.setModel(modelo);
        }
        
    }
    
    public void IniPant(){
    lbidCat.setText("1");
    lbRonda.setText("1");
    txPremio.setText("0");
    txNick.setText("");
    }
    public void HabOpc(boolean lOk){
        
        jrb1.setEnabled(lOk);
        jrb2.setEnabled(lOk);
        jrb3.setEnabled(lOk);
        jrb4.setEnabled(lOk);

        

    }
    public void LimpiarRadioButton(){
        txaPregunta.setText("");
        lbNumRandom.setText("");
        jrb1.setText("");
        jrb2.setText("");
        jrb3.setText("");
        jrb4.setText("");
        rdgOpciones.clearSelection();
        HabOpc(false);
        btnAleatoria.setFocusable(true);
    }
    public void HabMant(){
        ControladorCategoria conCat=new ControladorCategoria();
        Categoria cat=new Categoria();
        Conectar cnn=new Conectar();
        try {
            cat=conCat.getCategoria(cnn.obtener(), Integer.parseInt(lbidCat.getText()));
            lbCategoria.setText(cat.getsTipo());
            lbidCat.setText(Integer.toString(cat.getId()));
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
public void Visibles(){
    lbId.setVisible(false);
    lbrb1.setVisible(false);
    lbrb2.setVisible(false);
    lbrb3.setVisible(false);
    lbrb4.setVisible(false);
    lbidCat.setVisible(false);
    lbRonda.setVisible(false);
    lbNumRandom.setVisible(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgOpciones = new javax.swing.ButtonGroup();
        rgbPremio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pnBody = new javax.swing.JPanel();
        prb2 = new javax.swing.JProgressBar();
        prb3 = new javax.swing.JProgressBar();
        prb4 = new javax.swing.JProgressBar();
        prb5 = new javax.swing.JProgressBar();
        prb1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnOpcion = new javax.swing.JPanel();
        lbCategoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPregunta = new javax.swing.JTextArea();
        jrb1 = new javax.swing.JRadioButton();
        jrb2 = new javax.swing.JRadioButton();
        jrb3 = new javax.swing.JRadioButton();
        jrb4 = new javax.swing.JRadioButton();
        btnResponder = new javax.swing.JButton();
        btnAbandonarP = new javax.swing.JButton();
        lbrb2 = new javax.swing.JLabel();
        lbrb1 = new javax.swing.JLabel();
        lbId3 = new javax.swing.JLabel();
        lbrb3 = new javax.swing.JLabel();
        lbrb4 = new javax.swing.JLabel();
        lbNumRandom = new javax.swing.JLabel();
        btnAleatoria = new javax.swing.JButton();
        lbidCat = new javax.swing.JLabel();
        lbRonda = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txPremio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRanking = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        pnFoo = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        pnHead = new javax.swing.JPanel();
        lbNick = new javax.swing.JLabel();
        pnJugador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txNick = new javax.swing.JTextField();
        btnJugador = new javax.swing.JButton();
        rgbPunto = new javax.swing.JRadioButton();
        rgbDinero = new javax.swing.JRadioButton();
        lbId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenidos a JUEGO DE PREGUNTAS");

        jPanel1.setName("pnHead"); // NOI18N

        pnBody.setName("pnBody"); // NOI18N

        prb2.setBackground(new java.awt.Color(153, 255, 255));

        prb1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Level 1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Level 3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Level 2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Level 4");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Level 5");

        javax.swing.GroupLayout pnBodyLayout = new javax.swing.GroupLayout(pnBody);
        pnBody.setLayout(pnBodyLayout);
        pnBodyLayout.setHorizontalGroup(
            pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBodyLayout.createSequentialGroup()
                .addComponent(prb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(prb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(prb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(prb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(pnBodyLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(163, 163, 163)
                .addComponent(jLabel4)
                .addGap(146, 146, 146)
                .addComponent(jLabel3)
                .addGap(138, 138, 138)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(78, 78, 78))
        );
        pnBodyLayout.setVerticalGroup(
            pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prb2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prb3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prb4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prb1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnOpcion.setBackground(new java.awt.Color(204, 204, 204));

        lbCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txaPregunta.setEditable(false);
        txaPregunta.setColumns(20);
        txaPregunta.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txaPregunta.setRows(5);
        jScrollPane1.setViewportView(txaPregunta);

        rdgOpciones.add(jrb1);
        jrb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb1MouseClicked(evt);
            }
        });

        rdgOpciones.add(jrb2);

        rdgOpciones.add(jrb3);

        rdgOpciones.add(jrb4);

        btnResponder.setText("Seleccionar");
        btnResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderActionPerformed(evt);
            }
        });

        btnAbandonarP.setText("Abandonar");
        btnAbandonarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarPActionPerformed(evt);
            }
        });

        lbrb2.setEnabled(false);

        lbrb1.setEnabled(false);

        lbId3.setEnabled(false);

        lbrb3.setEnabled(false);

        lbrb4.setEnabled(false);

        lbNumRandom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnAleatoria.setText("Pregunta Aleatoria");
        btnAleatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatoriaActionPerformed(evt);
            }
        });

        lbidCat.setEnabled(false);

        jLabel7.setText("Premio");

        txPremio.setEditable(false);
        txPremio.setText("0");

        tblRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblRanking);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ranking");

        javax.swing.GroupLayout pnOpcionLayout = new javax.swing.GroupLayout(pnOpcion);
        pnOpcion.setLayout(pnOpcionLayout);
        pnOpcionLayout.setHorizontalGroup(
            pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOpcionLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(lbRonda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOpcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOpcionLayout.createSequentialGroup()
                        .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbrb4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbrb3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbrb1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbrb2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb4)
                            .addComponent(jrb3)
                            .addComponent(jrb2)
                            .addGroup(pnOpcionLayout.createSequentialGroup()
                                .addComponent(jrb1)
                                .addGap(18, 18, 18)
                                .addComponent(lbId3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnOpcionLayout.createSequentialGroup()
                                .addComponent(btnResponder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(189, 189, 189)
                                .addComponent(btnAbandonarP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOpcionLayout.createSequentialGroup()
                        .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addComponent(lbidCat, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txPremio, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAleatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOpcionLayout.createSequentialGroup()
                                .addComponent(lbNumRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(447, 447, 447)))))
                .addGap(292, 292, 292))
        );
        pnOpcionLayout.setVerticalGroup(
            pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOpcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnOpcionLayout.createSequentialGroup()
                        .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnOpcionLayout.createSequentialGroup()
                                .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNumRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnOpcionLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txPremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAleatoria))
                            .addGroup(pnOpcionLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(lbidCat, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnOpcionLayout.createSequentialGroup()
                                .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb1)
                                    .addComponent(lbId3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jrb2)
                                .addGap(18, 18, 18)
                                .addComponent(jrb3)
                                .addGap(18, 18, 18)
                                .addComponent(jrb4))
                            .addGroup(pnOpcionLayout.createSequentialGroup()
                                .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnOpcionLayout.createSequentialGroup()
                                        .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnOpcionLayout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(lbrb2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lbrb1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39))
                                    .addComponent(lbrb3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lbrb4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResponder)
                            .addComponent(btnAbandonarP))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOpcionLayout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRonda, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        pnBody.getAccessibleContext().setAccessibleName("pnBody");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFooLayout = new javax.swing.GroupLayout(pnFoo);
        pnFoo.setLayout(pnFooLayout);
        pnFooLayout.setHorizontalGroup(
            pnFooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFooLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        pnFooLayout.setVerticalGroup(
            pnFooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFooLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );

        lbNick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        pnJugador.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nick");

        txNick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txNickKeyReleased(evt);
            }
        });

        btnJugador.setText("Guardar");
        btnJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadorActionPerformed(evt);
            }
        });

        rgbPremio.add(rgbPunto);
        rgbPunto.setSelected(true);
        rgbPunto.setText("Jugar por Puntos");

        rgbPremio.add(rgbDinero);
        rgbDinero.setText("Jugar por Dinero");

        javax.swing.GroupLayout pnJugadorLayout = new javax.swing.GroupLayout(pnJugador);
        pnJugador.setLayout(pnJugadorLayout);
        pnJugadorLayout.setHorizontalGroup(
            pnJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnJugador)
                    .addGroup(pnJugadorLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNick, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(pnJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rgbPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rgbDinero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnJugadorLayout.setVerticalGroup(
            pnJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgbPunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJugador)
                    .addComponent(rgbDinero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbId.setEnabled(false);

        javax.swing.GroupLayout pnHeadLayout = new javax.swing.GroupLayout(pnHead);
        pnHead.setLayout(pnHeadLayout);
        pnHeadLayout.setHorizontalGroup(
            pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNick, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnHeadLayout.setVerticalGroup(
            pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeadLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNick, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(pnFoo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnFoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int nSalir=JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA ABANDONAR EL JUEGO? PERDERA TODO AVANCE ", "CONFIRMAR SALIR", JOptionPane.YES_NO_OPTION);
        if(nSalir==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(rootPane, "GRACIAS POR PARTICIPAR DE ESTE JUEGO");
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    public void TraerOpciones(int nPre){
     ArrayList<Opcion> opciones = new ArrayList<Opcion>();
        int cont=0;
        for(Component component: pnBody.getComponents()){
            component.setEnabled(true);
        }
        Conectar cnn=new Conectar();
        ControladorOpcion cOpciones=new ControladorOpcion();
        
        
        try {
            opciones=cOpciones.getAllPregunta(cnn.obtener(), nPre);
            for (Opcion opcione : opciones) {
            cont=cont+1;
            switch(cont){
                case 1:
                        jrb1.setText(opcione.getsRespuesta());
                        lbrb1.setText(Integer.toString(opcione.getId()));
                    break;
                case 2:
                        jrb2.setText(opcione.getsRespuesta());
                        lbrb2.setText(Integer.toString(opcione.getId()));
                    break;
                case 3:
                        jrb3.setText(opcione.getsRespuesta());
                        lbrb3.setText(Integer.toString(opcione.getId()));
                    break;
                case 4:
                        jrb4.setText(opcione.getsRespuesta());
                        lbrb4.setText(Integer.toString(opcione.getId()));
                    break;
                    
            }
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    
    private void btnJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadorActionPerformed
            Conectar cnn=new Conectar();
            control=new ControladorJugador();
        try {
            if(txNick.getText()!= ""){
                Jugador j=new Jugador();
                j.setsNick(txNick.getText());
                if(rgbPunto.isSelected()){
                    j.setTipo_Premio(0);
                }else{j.setTipo_Premio(1);}
                
               nId = control.guardar_jugador(cnn.obtener(), j);
               lbId.setText(Integer.toString(nId));
               sNick = j.getsNick();
               lbNick.setText("BIENVENIDO "+sNick);
                HabPan(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnJugadorActionPerformed
    
    public void ObtenerPremio(int nCat) throws ClassNotFoundException{
        ControladorRonda conRonda=new ControladorRonda();
        Conectar cnn=new Conectar();
        Ronda ronda=new Ronda();
        try {
            ronda=conRonda.getRonda(cnn.obtener(), nCat);
            int nIni=Integer.parseInt(txPremio.getText());
            txPremio.setText(Integer.toString(ronda.getDificultad()*nCat+nIni));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void btnResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderActionPerformed
        // TODO add your handling code here:
        ControladorOpcion cOp=new ControladorOpcion();
        Opcion opcion=new Opcion();
        int nOp=0;

        if(jrb1.isSelected()){
            nOp=Integer.parseInt(lbrb1.getText());
        }else if(jrb2.isSelected()){
            nOp=Integer.parseInt(lbrb2.getText());
        }else if(jrb3.isSelected()){
            nOp=Integer.parseInt(lbrb3.getText());
        }else if(jrb4.isSelected()){
            nOp=Integer.parseInt(lbrb4.getText());
        }else{
            JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR ALGUNA OPCION");
        }
        if(nOp>0){
            Conectar cnn=new Conectar();
            try {
                opcion=cOp.getOpcion(cnn.obtener(), nOp);
                if(opcion.isbCorrecta()){
                    JOptionPane.showMessageDialog(null, "CORRECTO");
                    
                    int nCat=Integer.parseInt(lbidCat.getText());
                    ObtenerPremio(nCat);
                    if(nCat==5){
                        JOptionPane.showMessageDialog(null, "FELICITACIONES, RETO SUPERADO. PUEDES VOLVER A INTENTARLO");         
                        lbRonda.setText("6");
                        GrardarEstadistica();
                        InicializarJuego();
                    }
                    if(nCat<5){
                    LimpiarRadioButton();
                    nCat=nCat+1;
                    
                    switch(nCat){
                        case 2:
                                prb2.setValue(100);
                            break;
                        case 3:
                               prb3.setValue(100);
                            break;
                        case 4:
                                prb4.setValue(100);
                            break;
                        case 5:
                                prb5.setValue(100);         
                            break;   
                    }
                    lbidCat.setText(Integer.toString(nCat));
                    lbRonda.setText(Integer.toString(nCat));
                    HabMant();
                    }
                       
                }else{
                    JOptionPane.showMessageDialog(null, "RESPUESTA EQUIVOCADA. GRACIAS POR PARTICIPAR.");
                     GrardarEstadistica();
                     InicializarJuego();

                }
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnResponderActionPerformed
     public boolean ValidarNick(){
      boolean lOk=true;
      if(lbId.getText()==""){
          lOk=false;
      }
      return lOk;
      
    }
    
     public void InicializarJuego(){
            LimpiarRadioButton();
            HabOpc(false);
            HabPan(false);
            IniPant();
            prb1.setValue(0);
            prb2.setValue(0);
            prb3.setValue(0);
            prb4.setValue(0);
            prb5.setValue(0);
        try {
            LlenarHistorico();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
            
     }
     
    public int DevolverIdPregunta(int nIndex){
        int nId=0;
        Conectar cnn=new Conectar();
        ControladorPregunta conPre=new ControladorPregunta();
        Pregunta pregunta=new Pregunta();
        ArrayList<Pregunta> preguntas = new ArrayList<Pregunta>();
        try {
            preguntas=conPre.getPreguntasCategorias(cnn.obtener(), Integer.parseInt(lbidCat.getText()));
            pregunta=preguntas.get(nIndex-1);
            nId=pregunta.getId();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return nId;
    }
    public void PreguntaAleatoria(){
        if(ValidarNick()){
            HabMant();
           HabOpc(true);
            Random r=new Random();
             int nAzar=r.nextInt(5)+1;
             if(nAzar==0){
             nAzar=1;
             }
             Conectar cnn=new Conectar();
             lbNumRandom.setText(Integer.toString(nAzar));
             ControladorPregunta conPre=new ControladorPregunta();
             Pregunta pregunta=new Pregunta();
             int nCat=0;
             if(lbidCat.getText()!=""){
                 nCat=Integer.parseInt(lbidCat.getText());
             }
             nAzar=DevolverIdPregunta(nAzar);
             try {
                 pregunta=conPre.getPregunta(cnn.obtener(), nAzar, nCat);
                 txaPregunta.setText(pregunta.getsPregunta());
                 TraerOpciones(nAzar);
             } catch (SQLException ex) {
                 Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
             }
             prb1.setValue(100);
       }else{
       JOptionPane.showMessageDialog(null, "INGRESE UN NICK PARA JUGAR");
       }
    }
    
    private void btnAleatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatoriaActionPerformed
        // TODO add your handling code here:
       PreguntaAleatoria();
        
    }//GEN-LAST:event_btnAleatoriaActionPerformed

    private void jrb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jrb1MouseClicked
    public void GrardarEstadistica(){
        if(lbId.getText()!=""){
                try {
                    ControladorEstadistica conEst=new ControladorEstadistica();
                    Estadistica estadistica=new Estadistica();
                    estadistica.setIdJugador(Integer.parseInt(lbId.getText()));
                    estadistica.setIdRonda(Integer.parseInt(lbRonda.getText())-1);
                    estadistica.setPremio(Integer.parseInt(txPremio.getText()));
                    Conectar cnn=new Conectar();
                    conEst.guardar_estadistica(cnn.obtener(), estadistica);
                } catch (SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        
    }
    private void btnAbandonarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarPActionPerformed
        // TODO add your handling code here:
        int nSalir=JOptionPane.showConfirmDialog(rootPane, "SEGURO DESEA ABANDONAR EL JUEGO?", "CONFIRMAR SALIR", JOptionPane.YES_NO_OPTION);
        if(nSalir==JOptionPane.YES_OPTION){
            GrardarEstadistica();
            
            JOptionPane.showMessageDialog(rootPane, "GRACIAS POR PARTICIPAR DE ESTE JUEGO"); 
            InicializarJuego();
        }
    }//GEN-LAST:event_btnAbandonarPActionPerformed

    private void txNickKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNickKeyReleased
        // TODO add your handling code here:
        int pos = txNick.getCaretPosition();
        txNick.setText(txNick.getText().toUpperCase());
        txNick.setCaretPosition(pos);
    }//GEN-LAST:event_txNickKeyReleased

    public void HabPan(boolean lOk){
        lbNick.setVisible(lOk);
        pnJugador.setVisible(!lOk);
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonarP;
    private javax.swing.JButton btnAleatoria;
    private javax.swing.JButton btnJugador;
    private javax.swing.JButton btnResponder;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton jrb1;
    private javax.swing.JRadioButton jrb2;
    private javax.swing.JRadioButton jrb3;
    private javax.swing.JRadioButton jrb4;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbId3;
    private javax.swing.JLabel lbNick;
    private javax.swing.JLabel lbNumRandom;
    private javax.swing.JLabel lbRonda;
    private javax.swing.JLabel lbidCat;
    private javax.swing.JLabel lbrb1;
    private javax.swing.JLabel lbrb2;
    private javax.swing.JLabel lbrb3;
    private javax.swing.JLabel lbrb4;
    private javax.swing.JPanel pnBody;
    private javax.swing.JPanel pnFoo;
    private javax.swing.JPanel pnHead;
    private javax.swing.JPanel pnJugador;
    private javax.swing.JPanel pnOpcion;
    private javax.swing.JProgressBar prb1;
    private javax.swing.JProgressBar prb2;
    private javax.swing.JProgressBar prb3;
    private javax.swing.JProgressBar prb4;
    private javax.swing.JProgressBar prb5;
    private javax.swing.ButtonGroup rdgOpciones;
    private javax.swing.JRadioButton rgbDinero;
    private javax.swing.ButtonGroup rgbPremio;
    private javax.swing.JRadioButton rgbPunto;
    private javax.swing.JTable tblRanking;
    private javax.swing.JTextField txNick;
    private javax.swing.JTextField txPremio;
    private javax.swing.JTextArea txaPregunta;
    // End of variables declaration//GEN-END:variables
}
